version: '3.3'
services:
  mail-push:
    build: ./server
    container_name: mdn-mail-push
    command: yarn prod:mail
    ports:
      - "3794:7001"
    restart: always
    networks:
      - defrecrut

  qrcode-generator:
    build: ./server
    container_name: mdn-qrcode-generator
    command: yarn prod:qrcode
    ports:
      - "3793:7002"
    restart: always
    networks:
      - defrecrut

  report:
    build: ./server
    container_name: mdn-report
    command: yarn prod:report
    ports:
      - "3792:7004"
    restart: always
    networks:
      - defrecrut

  score-manager:
    build: ./server
    container_name: mdn-score-manager
    command: yarn prod:score
    ports:
      - "3791:7003"
    restart: always
    networks:
      - defrecrut

  core:
    build: ./server
    container_name: defrecrut-core
    command: yarn prod:core
    ports:
      - "3790:7000"
    restart: always
    networks:
      - defrecrut

networks:
  defrecrut: